version: '3'
services:
    front:
      image: marvel-app/front
      build:
        context: ./
        dockerfile: front.dockerfile
      command: npm run serve -- --port 4040
      volumes:
        - ./client:/app
      ports:
        - "4040:4040"

